
* Some BibDesk Apple Scripts

** bibfetch.pl.scpt

This script does the following:
  1) For each selected BibDesk publication
  2) Passes the DOI if available or the quoted Title if no DOI to bibfetch.pl
  3) Parses the results of bibfetch.pl for the URL of the PDF
  4) Uses curl to download the PDF
  5) Attaches the PDF to the publication
  6) Auto-files the PDF

*** Installing bibfetch.pl  

In order to get [[https://github.com/mankoff/bibfetch][bibfetch.pl]] working download the script, and install
all of the dependencies it needs by typing something similar to the
following at the shell prompt:
 
 cpan install App::cpanminus
 and then
 cpanm Foo::Bar
 
 You might need to use "sudo" before cpan and cpanm

Customize this script to the location where you installed it.

** pdfmeat.py.scpt

This version takes one or more selected BibDesk records and fills in
missing information using Google Scholar search. If a DOI or title
exists in the record, it searches Google Scholar with pdfmeat.py. If a
PDF exists and no title, it uses pdfmeat to parse the PDF and then
searches Google Scholar.

Various fields returned by the search are filled in to each existing
record. Nothing is overwritten.

*** Dependencies

This script uses [[http://github.com/mankoff/pdfmeat][pdfmeat]]. You should it installed and working from the
command line, and then modify this script so it can access it.

pdfmeat is a Python script and it relies on pdftotext among other
things. You should have that installed if you use LaTeX. It also
depends on a variety of Python modules.

